### ISSUE TITLE
Interesting project

### ISSUE THREAD

**Issue by simon-rob** [fm4dd/pi-bno080#1]
The source files seem to be missing. Are you going to make them available?

Regards, 

Simon

**Comment by simon-rob** [comment]
bump

**Comment by fm4dd** [comment]
Hi Simon,

The work got stuck in early stages, I planned to check-in after sorting out issues first (issues.md). If only I could get time to spend more work on this cool sensor... I just checked in the early code fragments.

Cheers, Frank

**Comment by simon-rob** [comment]
Thanks Frank,

I haven't tried it yet, I have only looked at the code. 
Looking at SendPacket I don't see a free for the malloc is it freed somewhere else?

Regards,

Simon
