### ISSUE TITLE
Doesn't compile on buster

### ISSUE THREAD

**Issue by sezeryalcin** [fm4dd/pi-bno080#2]
cc i2c_bno080.o getbno080.o -o getbno080 
/usr/bin/ld: i2c_bno080.o: in function `qToFloat':
/root/pi-bno080-master/i2c_bno080.c:979: undefined reference to `pow'
/usr/bin/ld: /root/pi-bno080-master/i2c_bno080.c:979: undefined reference to `pow'
/usr/bin/ld: /root/pi-bno080-master/i2c_bno080.c:979: undefined reference to `pow'
/usr/bin/ld: /root/pi-bno080-master/i2c_bno080.c:979: undefined reference to `pow'
/usr/bin/ld: /root/pi-bno080-master/i2c_bno080.c:979: undefined reference to `pow'
collect2: error: ld returned 1 exit status
make: *** [Makefile:14: getbno080] Error 1

**Comment by fm4dd** [comment]
Thank you for reporting! Fixed by adding -lm in Makefile to link against the math library.

Cheers,
Frank
